### ISSUE TITLE
Initalizing Hexo in an existing git repository deletes the .git folder.

### ISSUE THREAD

**Issue by terrycloth** [hexojs/hexo#1749]
I have a git repository for one of my websites, originally started with another static site generator. But I thought I'd try out Hexo.

Maybe it would have been cleaner to start from an empty directory, but I started a new branch in my repository and felt safe enough working from there. So I ran `hexo init .` in the root of the repository. This deleted the `.git/` folder, and now all my local data on the repository history is gone. I had not pushed all the commits just before I started this, so I have lost a few days' work.

Perhaps if Hexo detects that it's not being run in an empty directory, it should print a warning _and then exit_ instead of wiping the existing git history.

**Comment by leesei** [comment]
Sorry about the incident.

@tommy351 I think we need to add check and prompt for confirmation in
https://github.com/hexojs/hexo-cli/blob/master/lib/console/init.js

**Comment by krzysztof-sikorski** [comment]
Maybe you could initialize Hexo in a temporary directory and then, when all files are ready, just copy/move them to target directory? That way there would be no need to touch `.git` folder at all.

**Comment by leesei** [comment]
@krzysztof-sikorski Good suggestion, [sindresorhus/os-tmpdir](https://github.com/sindresorhus/os-tmpdir) may be useful

**Comment by Xuanwo** [comment]
https://github.com/hexojs/hexo/issues/1740 is the same but in `deploy`.

**Comment by phoenixjiangnan** [comment]
terrible bug!

**Comment by dotmacro** [comment]
This happened to me too. I was fortunate enough to have a remote backup, but still lost a few days' work. :-(

Is Hexo compatible with git? Does the site/hexo need to be in a sub-directory, or will .git be safe if I initialize Hexo in a temp sub-directory and then just copy/move Hexo files to the main directory?

**Comment by leesei** [comment]
It is intended for Hexo to be init-ed in an empty directory, see #12.

**Comment by dotmacro** [comment]
[hexojs/hexo-cli#12](https://github.com/hexojs/hexo-cli/issues/12) is about a non-global Hexo install, and doesn't mention init-ing in empty directories, unless I'm misunderstanding something. 

The documentation doesn't state Hexo should be init-ed in an empty directory. This should be mentioned in the [setup](https://hexo.io/docs/setup.html) instructions, and as @terrycloth suggested, if Hexo detects that it's being run in a non-empty directory, Hexo should print a warning and _then exit instead of wiping the existing git history_.

**Comment by leesei** [comment]
The init command is provided by `hexo-cli/lib/console/init.js`.
hexo has dependency on hexo-cli.

This issue is fixed with https://github.com/hexojs/hexo-cli/pull/14, pending merge.
@tommy351 please check the PR.

**Comment by cocobear** [comment]
Why this bug still not fixed?

**Comment by lukaMis** [comment]
My .git folder was deleted as too. What is correct way to resolve this issue and why this still was not fixed after one year?

**Comment by airbr** [comment]
I wish to express my significant annoyance that this bug is not fixed yet.... Luckily just happened to a simple/small project.

**Comment by nbkhope** [comment]
+1

**Comment by leesei** [comment]
@lukaMis the right way is to `hexo init` a new folder and copy your posts/config to it.
PR is created but I do not have to right to merge.

**Comment by leesei** [comment]
closed via hexojs/hexo-cli#14

**Comment by NoahDragon** [comment]
@leesei Yeah, closed.

**Comment by StoneCypher** [comment]
This just happened to me.  Please consider re-opening; believed not fixed.

**Comment by NoahDragon** [comment]
@StoneCypher Although the PR has merged, the npm package hasn't updated yet.

**Comment by StoneCypher** [comment]
Ah, gotcha.
