### ISSUE TITLE
bug in keywords meta tag used for SEO.

### ISSUE THREAD

**Issue by raphaklaus** [hexojs/hexo#1828]
Hello!

First of all, thank you for all involved people in Hexo. This tools is great!

In the #1683 PR the keywords meta tag was include in Hexo. However, it's not working even if the post has tags.

I've suggested a simple fix in my pull request: #1827

**Comment by leesei** [comment]
This is indeed a bug, and our test case is wrong.
The tests should follow the schema in `lib/models/` when creating stub object, sorry for the confusion.

We should use `toArray()` in `open_graph.js` and fix the test cases.

**Comment by sephXD** [comment]
This bug is fixed in #2278 .

**Comment by rafaltrojanowski** [comment]
I still have this issue, I'm using the default theme, `landscape`

Added comma-separated keywords in the main `_config`, not the theme one.

I can only see multiple: <meta property="article:tag" content="keyword">
which is okay, but meta keywords are still missing. It works that way for all pages. Isn't it a bug?
