### ISSUE TITLE
ERROR Local hexo not found

### ISSUE THREAD

**Issue by saltares** [hexojs/hexo#2076]
I am unable to run the `hexo` command inside a hexo blog directory.

```
dsaltares@saltares:/home/dsaltares/hexo_blog: hexo
ERROR Local hexo not found in ~/hexo_blog
ERROR Try running: 'npm install hexo --save'
```

The `--save` option does nothing really.

However I did install `hero-cli` and `hero-server` using `npm install -g`.

I am using nvm to manage node versions.

```
dsaltares@saltares:/home/dsaltares/hexo_blog: nvm --version
0.31.4
```

```
dsaltares@saltares:/home/dsaltares/hexo_blog: node -v
v6.3.1
```

```
dsaltares@saltares:/home/dsaltares/hexo_blog: npm --v
3.10.3
```

The same also happens with node 4 and node 5.

**Comment by junbaor** [comment]
###  I have the same problem.

```
git version 1.9.1
node version v4.5.0
npm version 2.15.9
```

**Comment by ishu3101** [comment]
**I'm having the same problem on windows as well.**

```
Windows 10
git version: 2.9.0
node version: v6.6.0
npm version: 3.10.3
```

**Comment by yudianguo** [comment]
vagrant 
i have the same problem on vagrant

**Comment by NoahDragon** [comment]
Same here.

**Comment by KIDJourney** [comment]
Same here

**Comment by vectorzeng** [comment]
same here

**Comment by NoahDragon** [comment]
I don't know the reason, but somehow [my config](https://github.com/NoahDragon/Vagrantfile/blob/master/4.hexo/Vagrantfile) is working.

**Comment by noinfo** [comment]
Same here. Just installed a plugin and updated to the latest hexo version and hexo stopped working. It ran all day without a hitch, plugin install and hexo update and its "gone". Plugin uninstall did not change anything.

`○ → hexo serve
ERROR Local hexo not found in unicante-hexo
ERROR Try running: 'npm install hexo --save'`

**Comment by Shane24** [comment]
Any fix for this? Am having the same issue

**Comment by NoahDragon** [comment]
@Shane24 I have this issue before, but somehow reinstall the npm environment, the issue is gone. No ideas how exactly to fix this.

**Comment by ovasquez** [comment]
This seems like an important bug. I installed hexo today on a clean environment (latest stable NodeJS), the node-gyp is successfully installed but I get the same error:
```
ERROR Local hexo not found in hexo\site
ERROR Try running: 'npm install hexo --save'
```

**Comment by zimplexing** [comment]
i fixed it,and i reinstall the `npm install -g node-gyp ` you can have a try

**Comment by bucketzxm** [comment]
I have the same problem... `npm install -g node-gyp` didn't solve this problem...:(

**Comment by Code2Life** [comment]
Same here...

**Comment by oikewll** [comment]
same here

**Comment by 2lei** [comment]
same here

**Comment by aimer1124** [comment]
same here [https://github.com/aimer1124/aimer1124.github.io/tree/raw](https://github.com/aimer1124/aimer1124.github.io/tree/raw)

**Comment by cbellei** [comment]
I had the same problem. I uninstalled and then reinstalled node.js through homebrew and now things are working again. Go figure...

**Comment by JohannHospice** [comment]
A solution that worked for me to is removing the **node_modules/** directory and reinstall it, so run: 
`rm -rf node_modules/ && npm install`

**Comment by aimer1124** [comment]
Thanks @JohannHospice @cbellei .
According @JohannHospice solution, my steps are below:

1. delete the cache,[change travis file](https://github.com/aimer1124/aimer1124.github.io/commit/a585a9e9d40fa575c19a1308c264359902019036)
2. hexo clean, hexo generate . Everything goes well
3. Add the cache again, It still goes well. [Add the cache in travis file](https://github.com/aimer1124/aimer1124.github.io/commit/40e210093af8f4ffcb3b32e84d9b96c65241675e)

**Comment by zjien** [comment]
@JohannHospice Thanks,it works

**Comment by iwiilbeback** [comment]
@JohannHospice Thanks,it works

**Comment by flyer88** [comment]
@JohannHospice Thanks,it works!!

**Comment by NoahDragon** [comment]
Close this issue, as @JohannHospice provided the solution.

**Comment by 2016lkaust** [comment]
I have tried as JohannHospice said,but it seems that it doesn't work.
(I attemped to upload a screenshot,but failed)
```
LOOK@PC-2015 MINGW64 /e/blog/2016lkaust.github.io
$ npm install
npm WARN deprecated swig@1.4.2: This package is no longer maintained
npm WARN prefer global marked@0.3.6 should be installed with -g

> dtrace-provider@0.8.1 install E:\blog\2016lkaust.github.io\node_modules\dtrace-provider
> node scripts/install.js

LOOK@PC-2015 MINGW64 /e/blog/2016lkaust.github.io
$ hexo
ERROR Local hexo not found in E:\blog\2016lkaust.github.io
ERROR Try running: 'npm install hexo --save'

LOOK@PC-2015 MINGW64 /e/blog/2016lkaust.github.io
$
```

**Comment by NoahDragon** [comment]
@2016lkaust  This is an know issue and will be fixed in next build.

**Comment by lc1838228782** [comment]
@JohannHospice Thanks

**Comment by Spike-Leung** [comment]
@JohannHospice thanks a lot . i meet this error after installed hexo-migrator-rss plugin. may be there something wrong

**Comment by JerryChu** [comment]
hexo 3.4.4, still has this problem.

**Comment by haodongguo520** [comment]
same here

**Comment by xpgeng** [comment]
After reinstalling npm using `nvm install stable`, and again using the method of @JohannHospice, `rm -rf node_modules/ && npm install`. 

I fixed my error. Hope it works.

**Comment by yushengyuan1993** [comment]
@JohannHospice   nice and thx!

**Comment by Anakinliu** [comment]
maybe your **nodejs version is too old**.
[see here](https://github.com/hexojs/hexo/issues/2978)

**Comment by bobliaos** [comment]
@Anakinliu reinstalled Nodejs,then it worked,thx!

**Comment by TinyCalf** [comment]
@xpgeng `-rf node_modules/ && npm install` this works in my situation

**Comment by changwei0708** [comment]
maker

**Comment by changwei0708** [comment]
to all , update nodejs to latest version and exec rm -rf node_modules/ && nam install ,it work for me !

**Comment by changwei0708** [comment]
mac os update nodejs 
Here's how I successfully upgraded from v0.8.18 to v0.10.20 without any other requirements like brew etc, (type these commands in terminal):

sudo npm cache clean -f (force) clear you npm cache
sudo npm install -g n install "n" (this might take a while)
sudo n stable upgrade to lastest version
Note that sudo might prompt your password.

If the version number doesn't show up when typing node -v, you might have to reboot.

these instructions are found here as well: davidwalsh.name/upgrade-nodejs

**Comment by jnuhwb** [comment]
upgrade nodejs works for me.

**Comment by xmuyoucai** [comment]
run `npm install hexo --save` in base directory of blog, this works for me

**Comment by yaoxin940211** [comment]
> upgrade nodejs works for me.

so am i

**Comment by weiqifa0** [comment]
???

**Comment by GerhardMes** [comment]
I have the same problem. I have tried all the above-mentioned solution, but nothing worked out.
The problem accrued after doing some tricks in the theme (I am using Hueman)
any advice how to fix this?

**Comment by GerhardMes** [comment]
Found the solution.
manually deleted the whole node folder and installed it again with "npm install" within my hexo folder.
That is my solution - for me it worked out fine.

**Comment by mduccc** [comment]
> A solution that worked for me to is removing the **node_modules/** directory and reinstall it, so run:
> `rm -rf node_modules/ && npm install`

Good. It's working.

**Comment by imoyao** [comment]
hope this will help somebody: in my case i upgrade node from v8.11.2 to v14.*, and then it works
