### ISSUE TITLE
TOC seems not suitable when there is a link in headers.

### ISSUE THREAD

**Issue by xuelangZF** [hexojs/hexo#2137]
When there is a link in the header, such as:

```
# Header1

Content....

# [Header2](http://selfboot.cn)

content...

## Sub Header

content...
```

Then the toc generated seems a bit strange, just looks like:

```
<ol class="toc">
<li class="toc-item toc-level-1">
...
</ol>
<li class="toc-item toc-level-1"><a class="toc-link" href="#Sub Header"><span class="toc-number">2.</span> <span class="toc-text">Sub Header</span></a></li>
...
```

Should not all the `<li class="toc-item toc-level-*">` be  in `ol.toc` ?

Version:

```
$ hexo --version
hexo: 3.2.2
hexo-cli: 1.0.2
os: Darwin 15.6.0 darwin x64
http_parser: 2.7.0
node: 6.4.0
v8: 5.0.71.60
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2h
```

And in [this blog](http://selfboot.cn/2016/06/13/python_performance_analysis/), there is a live demo.

**Comment by NoahDragon** [comment]
Seems it has been resolved on your site.

**Comment by xuelangZF** [comment]
I have not resolved this issue.

As you can see, in my blog, the structure is as follows:

![image](https://cloud.githubusercontent.com/assets/2769831/25689029/9bc8b0de-30b6-11e7-9d63-864e2d16ffbc.png)

But it should be as follows:

![image](https://cloud.githubusercontent.com/assets/2769831/25689036/a7345036-30b6-11e7-9422-0ba20249cb04.png)

**Comment by SukkaW** [comment]
I think I might know what is happened here.

The title `timeit` in your post is `<h1>` (`#`) while the subtitle under (likes `命令行接口` and `Python 接口`) are in `<h3>` (`###`).

So far there is no better way to fix that issue, all we could suggest is not to skip any level of headings now.

We will keep this issue opened until we came up with some better idea to solve this.

**Comment by stevenjoezhang** [comment]
See also https://github.com/theme-next/hexo-theme-next/issues/882#issuecomment-494267056

**Comment by SukkaW** [comment]
@stevenjoezhang It appears that @ppoffice has already fix the issue in his icarus theme. Maybe we could borrow some idea from it.

**Comment by stevenjoezhang** [comment]
See also https://github.com/ppoffice/hexo-component-inferno/blob/a02bd8fa7675b8aa60559e9e9549ec192a2ba5ee/src/view/widget/toc.jsx

**Comment by jerryc127** [comment]
是否有计划修复这个问题？
@stevenjoezhang @SukkaW

**Comment by stevenjoezhang** [comment]
@jerryc127 恐怕这个问题无法被修复。例如，用户给出一个完全非法的 heading 顺序： h1, h3, h4, h2, h5, h1 你认为 Hexo 输出什么结果是合理的？

**Comment by stevenjoezhang** [comment]
Fixed in #5653
