### ISSUE TITLE
Multiple config files results in 'Local hexo not found'

### ISSUE THREAD

**Issue by benc-uk** [hexojs/hexo#2531]
## Environment Info

Node version(`node -v`): 6.10.1

Your site `_config.yml` (Optional):

Your theme `_config.yml` (Optional): 

Hexo and Plugin version(`npm ls --depth 0`): 
```
hexo-site@0.0.0 C:\Dev\blog
+-- hexo@3.3.1
+-- hexo-deployer-ftpsync@0.1.1
+-- hexo-deployer-git@0.2.0
+-- hexo-generator-archive@0.1.4
+-- hexo-generator-category@0.1.3
+-- hexo-generator-feed@1.2.0
+-- hexo-generator-index@0.2.1
+-- hexo-generator-tag@0.2.0
+-- hexo-migrator-wordpress@0.1.2
+-- hexo-renderer-ejs@0.2.0
+-- hexo-renderer-marked@0.2.11
+-- hexo-renderer-stylus@0.3.3
+-- hexo-server@0.2.0
`-- hexo-tag-fontawesome@1.0.0
```
#### 2. Reproduce:
This works fine
```
hexo serve --config config.yml
```
This result in an error "Local hexo not found":
```
hexo serve --config config.yml,config-bc.yml
```
Both config yml files exist and have no special permissions 

Here is a screenshot
![2017-04-21_182033](https://cloud.githubusercontent.com/assets/14982936/25288984/bad12322-26bf-11e7-8b1c-7c7057753d98.png)

#### 3. Log
```
PS C:\Dev\blog> hexo serve --config config.yml,config-bc.yml --debug
17:27:09.630 ERROR Local hexo not found in C:\Dev\blog
17:27:09.633 ERROR Try running: 'npm install hexo --save'
```

**Comment by NoahDragon** [comment]
Thanks for raising this issue. It has been fixed in #2520, will be available in next build.

**Comment by orloxx** [comment]
I can still reproduce this issue in current v3.3.1

Node `v6.10.1`

```
├── hexo@3.3.1
├── hexo-generator-archive@0.1.4
├── hexo-generator-category@0.1.3
├── hexo-generator-index@0.2.1
├── hexo-generator-tag@0.2.0
├── hexo-renderer-ejs@0.2.0
├── hexo-renderer-marked@0.2.11
├── hexo-renderer-stylus@0.3.3
└── hexo-server@0.2.0
```
